WM Class 4 - Pakize Bozkurt - SQL - Week 1
CodeYourFuture/Full-Stack-Project-Assessment pull request #157
Opened 2023-01-17 21:13 UTC by PakizeBozkurt

2023-01-25 21:22 UTC, SallyMcGrath requested changes
Thanks for this @PakizeBozkurt. I can see you've put a lot of effort into this so far.

I think there's some work to do. I can't see your Lighthouse report in the files and I'm not sure all the requirements in Level 100 have been met. Take a look through and have a think about some of the questions I've raised. 

When you ran Lighthouse, what did the report say? What changes should you make? (I ran Lighthouse on your code.)

2023-01-25 21:22 UTC, SallyMcGrath commented on client/src/companents/Main.jsx
> +          <DeleteBtn videos={setVideos} id={video.id} data={videos}/>
What happens when you press this button?

2023-01-25 21:22 UTC, SallyMcGrath commented on client/src/companents/Main.jsx
> +    //console.log(videos);
Please remove commented out code.
```suggestion
```

2023-01-26 20:05 UTC, PakizeBozkurt commented on client/src/companents/Rating.jsx
> +        onClick={() => handleDicrease()}
:+1:

2023-01-26 20:15 UTC, PakizeBozkurt commented on client/src/companents/Videos.jsx
> +            title="Embedded youtube"
title={props.videos.id}

2023-01-26 20:17 UTC, PakizeBozkurt commented on client/src/companents/Main.jsx
> +import dataVideos from "/home/codeyourfuture/Documents/SQL/W-2/Full-Stack-Project-Assessment/client/src/exampleresponse.json";
It was hardcode from json package. I am getting all data from database.

2023-01-26 20:18 UTC, PakizeBozkurt commented on client/src/companents/Rating.jsx
> +        style={{ margin: "20px" }}
:smile_cat:  CSS :+1:

2023-01-26 20:18 UTC, PakizeBozkurt commented on client/src/companents/Videos.jsx
> +            style={{ height: "500px", weihgt: "200px" }}
:+1:

2023-01-26 20:20 UTC, PakizeBozkurt commented on client/src/companents/Main.jsx
> +    //console.log(videos);
I removed them. :+1:

2023-01-26 20:28 UTC, PakizeBozkurt commented
> Thanks for this @PakizeBozkurt. I can see you've put a lot of effort into this so far.
> 
> I think there's some work to do. I can't see your Lighthouse report in the files and I'm not sure all the requirements in Level 100 have been met. Take a look through and have a think about some of the questions I've raised.
> 
> When you ran Lighthouse, what did the report say? What changes should you make? (I ran Lighthouse on your code.)


Thank you so much @SallyMcGrath . 
I just did my best so far.

I ran Lighthouse on my code. I attached it in the bellow. :arrow_double_down: 
![Screenshot from 2023-01-26 20-14-10](https://user-images.githubusercontent.com/97640517/214942968-6bbcdca5-f88b-49d6-9590-b6ecea52243f.png)

Have a fabulous week!

2024-04-08 14:24 UTC, closed without merging